[serviceweaver]
name = "weaver-start"
# binary = "./weaver-start"
binary = "./weaver-start.exe"
rollout = "3m"

[gke]
regions = ["asia-northeast3"]
public_listener = [
  {name = "weaver-start", hostname = "weaver.myyrakle.com"},
]


